# Generated by Django 2.0 on 2017-12-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171209_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.UUIDField(db_index=True, unique=True)),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
